sudo: required
dist: bionic
language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - android-28
    - build-tools-28.0.3
    - extra-android-m2repository

script:
- ./gradlew clean assemble
