sudo: required
dist: bionic
language: android

jdk:
  - openjdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - extra-google-m2repository

before_install:
  - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "cmake;3.10.2.4988404"
  - echo y | sdkmanager "lldb;3.1"

script:
- export PATH=$PATH:$ANDROID_HOME/ndk-bundle
- export LOWPERF=true
- ./gradlew clean assemble
