language: android
sudo: true

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "ndk;20.0.5594570"
  - echo y | sdkmanager "cmake;3.10.2.4988404"

script:
- export PATH=$PATH:$ANDROID_HOME/ndk-bundle
- export LOWPERF=true
- ./gradlew clean assemble
